### ISSUE TITLE
能否提供编译的详细步骤

### ISSUE THREAD

**Issue by zhanghanduo** [ViewFaceCore/SeetaFace6OpenBinary#1]
你好，请问能否提供一下编译的详细步骤？
我在WIN(MSVC, MingGW)\Linux (GCC)平台下进行编译，会有各种问题和错误，如果能提供一下比较好的编译脚本或者步骤的话感激不尽！

**Comment by withsalt** [comment]
参考：https://github.com/ViewFaceCore/ViewFaceCore/blob/main/docs/SeetaFace_Build.md
